### ISSUE TITLE
Install VLLMs using InferenceService

### ISSUE THREAD

**Issue by dmartinol** [opendatahub-io/llama-stack-demos#47]
Wouldn't be more RHOAI oriented to deploy the vLLM instances using `InferenceService` resources instead?

**Comment by cooktheryan** [comment]
@dmartinol completely agree. Timing and GPU contention has been the issue we have been fighting against. Now that we are shrinking the models used we will flip over to Inferenceservice. 

Time has been our enemy but great suggestion!

**Comment by dmartinol** [comment]
adding a sample manifest to deploy to InferenceServices, one using OCI container and another from an S3 bucket:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: granite-3.1-8b
    serving.knative.openshift.io/enablePassthrough: "true"
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: "true"
  name: granite-31-8b
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --enable-auto-tool-choice
      - --tool-call-parser
      - granite
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: granite-31-8b
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.1-8b-instruct-quantized.w4a16
    tolerations:
    - effect: NoSchedule
      key: p4-gpu
      operator: Exists
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: parasol-financial
    serving.knative.openshift.io/enablePassthrough: "true"
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    networking.knative.dev/visibility: cluster-local
    opendatahub.io/dashboard: "true"
  name: parasol-financial
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --distributed-executor-backend=mp
      - --max_model_len=128640
      - --enable-auto-tool-choice
      - --tool-call-parser
      - granite
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
      runtime: parasol-financial
      storage:
        key: minio
        path: models/parasol-financial
    tolerations:
    - effect: NoSchedule
      key: p4-gpu
      operator: Exists
```
